import {test,expect} from '@playwright/test';
import {readFile,mkdir} from 'node:fs/promises';
import {Buffer} from 'node:buffer';
const evidence='test-results/g18-evidence';
test('G18 real 15-scenario checklist and default-denied release matrix at 1280x720 and 200% zoom',async({page})=>{
 await mkdir(evidence,{recursive:true});
 await page.setViewportSize({width:1280,height:720});
 await page.goto('/#/technik');
 const board=page.getByRole('region',{name:'G18 Generalprobe und Release-Sperren'});
 await expect(board).toBeVisible();
 await expect(board).toContainText('NO-GO · KEINE FREIGABE');
 const group=board.getByRole('group',{name:'15 Probeszenarien'});
 await expect(group.getByRole('button')).toHaveCount(15);
 const gates=board.getByRole('table',{name:'Release-Status nach Eigentümerschaft'});
 await expect(gates.getByRole('row')).toHaveCount(7);
 await expect(gates).not.toContainText('FREIGEGEBEN');
 await board.screenshot({path:evidence+'/g18-checklist-desktop-1280x720.png'});
 const button=group.getByRole('button',{name:/Quiztafel · 5 Teams/});
 await button.click();
 await expect(button).toHaveAttribute('aria-pressed','true');
 const active=board.getByRole('group',{name:'Ausgewähltes Probeszenario'});
 await active.getByRole('combobox',{name:'Status: Beamer und Leseabstand'}).selectOption('reported');
 await active.getByRole('combobox',{name:'Status: Absturz und Wiederherstellung'}).selectOption('defect');
 await active.getByRole('textbox',{name:'Beobachtungen und offene Defekte'}).fill('Reale Veranstaltung noch nicht getestet');
 await expect(board).toContainText('1 beobachtet notierte Prüfschritte');
 await expect(board).toContainText('1 Probleme');
 await group.getByRole('button',{name:/Rundenquiz · 3 Teams/}).click();
 await group.getByRole('button',{name:/Quiztafel · 5 Teams/}).click();
 await expect(active.getByRole('combobox',{name:'Status: Absturz und Wiederherstellung'})).toHaveValue('defect');
 const file=Buffer.from('synthetic G18 browser fixture');
 await active.getByLabel(/Optionale lokale Belegdatei/).setInputFiles({
   name:'fixture-g18.txt',mimeType:'text/plain',buffer:file,
 });
 await expect(active).toContainText('Lokaler Datei-Fingerabdruck');
 await expect(active).toContainText('fixture-g18.txt');
 await page.setViewportSize({width:640,height:800});
 await page.evaluate(()=>{globalThis.document.documentElement.style.zoom='2';});
 await expect(board).toBeVisible();
 await active.getByRole('combobox',{name:'Status: Beamer und Leseabstand'}).focus();
 await expect(active.getByRole('combobox',{name:'Status: Beamer und Leseabstand'})).toBeFocused();
 await board.screenshot({path:evidence+'/g18-checklist-host-200percent.png'});
 expect(await board.evaluate(el=>el.scrollWidth<=el.clientWidth+3)).toBe(true);
 await expect(board).toContainText('NO-GO');
});
test('G18 signed-looking but actually unsigned notes reject tampering and cannot unlock owner gate',async({page})=>{
 await page.goto('/#/technik');
 const board=page.getByRole('region',{name:'G18 Generalprobe und Release-Sperren'});
 const active=board.getByRole('group',{name:'Ausgewähltes Probeszenario'});
 await active.getByRole('combobox',{name:'Status: Beamer und Leseabstand'}).selectOption('reported');
 const saved=page.waitForEvent('download');
 await board.getByRole('button',{name:'G18-Protokoll als JSON exportieren'}).click();
 const file=await saved, bytes=await readFile(await file.path());
 const data=JSON.parse(bytes.toString('utf8'));
 expect(data.packet.rows).toHaveLength(15);
 expect(data.packet.releaseGates).toHaveLength(6);
 expect(data.packet.decision).toBe('NO_GO');
 expect(data.packet.ownerApproved).toBe(false);
 const upload=board.getByLabel('G18-Protokoll lokal importieren');
 await upload.setInputFiles({name:'g18-valid.json',mimeType:'application/json',buffer:bytes});
 await expect(board).toContainText('15 Szenarien und G17-Quellenanker konsistent');
 const forged=JSON.parse(bytes.toString('utf8'));
 forged.packet.releaseGates[0].status='APPROVED';
 forged.packet.ownerApproved=true;
 await upload.setInputFiles({name:'g18-forged.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(forged))});
 await expect(board).toContainText('Prüfpaket ABGELEHNT');
 await expect(board).toContainText('NO-GO · KEINE FREIGABE');
 await expect(board.getByRole('table',{name:'Release-Status nach Eigentümerschaft'}).getByRole('cell',{name:'OFFEN'})).toHaveCount(6);
});
